/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package medicalportal;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Ritika Tiwari
 */
public class Company extends javax.swing.JFrame {

    /**
     * Creates new form Company
     */
    public Company() {
        initComponents();
        selectMod();
    }
    
    
    
    
     Connection con = null;
    Statement st = null;
    ResultSet rs = null;
    java.util.Date MDate,EDate;
    java.sql.Date Mfd , Exp;
    
    
    
    
     private void selectMod(){
        
       try{
           con =DriverManager.getConnection("jdbc:mysql://localhost:3306/medicaldb","root","Ritika@1910");
           st = con.createStatement();
           rs = st.executeQuery("select * from companytb");
           comptable.setModel(DbUtils.resultSetToTableModel(rs));
       } 
       catch(SQLException e){
           JOptionPane.showMessageDialog(this, "Enter Details....");
           //e.printStackTrace();
       }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        add = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cid = new javax.swing.JTextField();
        cphone = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        update = new javax.swing.JButton();
        cname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        delete = new javax.swing.JButton();
        cadd = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        comptable = new javax.swing.JTable();
        cexp = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 102, 255));
        jPanel1.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("EXPERIENCE");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(360, 80, 130, 38);

        add.setBackground(new java.awt.Color(51, 51, 255));
        add.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        add.setForeground(new java.awt.Color(51, 51, 51));
        add.setText("ADD");
        add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addMouseClicked(evt);
            }
        });
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        jPanel1.add(add);
        add.setBounds(133, 304, 95, 34);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("ID");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(12, 84, 109, 38);

        cid.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        cid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cidActionPerformed(evt);
            }
        });
        jPanel1.add(cid);
        cid.setBounds(158, 89, 173, 28);

        cphone.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jPanel1.add(cphone);
        cphone.setBounds(500, 140, 173, 28);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("ADDRESS");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(12, 178, 109, 38);

        jLabel2.setBackground(new java.awt.Color(51, 51, 255));
        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("COMPANIES LIST");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(260, 350, 206, 38);

        update.setBackground(new java.awt.Color(51, 51, 255));
        update.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        update.setForeground(new java.awt.Color(51, 51, 51));
        update.setText("UPDATE");
        update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateMouseClicked(evt);
            }
        });
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        jPanel1.add(update);
        update.setBounds(421, 304, 120, 34);

        cname.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jPanel1.add(cname);
        cname.setBounds(158, 133, 173, 28);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("NAME");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(12, 128, 109, 38);

        delete.setBackground(new java.awt.Color(51, 51, 255));
        delete.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        delete.setForeground(new java.awt.Color(51, 51, 51));
        delete.setText("DELETE");
        delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteMouseClicked(evt);
            }
        });
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        jPanel1.add(delete);
        delete.setBounds(270, 300, 120, 34);

        cadd.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jPanel1.add(cadd);
        cadd.setBounds(158, 183, 173, 28);

        jLabel9.setBackground(new java.awt.Color(51, 51, 255));
        jLabel9.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("Manage COMPANY");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(260, 20, 250, 38);

        comptable.setBackground(new java.awt.Color(51, 51, 255));
        comptable.setForeground(new java.awt.Color(51, 51, 51));
        comptable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        comptable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comptableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(comptable);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(0, 400, 690, 220);

        cexp.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jPanel1.add(cexp);
        cexp.setBounds(500, 90, 173, 28);

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("PHONE");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(370, 130, 109, 38);

        jLabel7.setBackground(new java.awt.Color(0, 51, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/medicalcleanse_com.png"))); // NOI18N
        jPanel1.add(jLabel7);
        jLabel7.setBounds(0, 20, 690, 400);

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-logout-rounded-left-30.png"))); // NOI18N
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel11);
        jLabel11.setBounds(10, 0, 40, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 623, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(690, 623));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addActionPerformed

    private void cidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cidActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteActionPerformed

    private void addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseClicked
        // TODO add your handling code here:
//         MDate = medmfd.getDate();
//        Mfd = new java.sql.Date(MDate.getTime());
//        EDate = medexp.getDate();
//        Exp = new java.sql.Date(EDate.getTime());

        try{
            con =DriverManager.getConnection("jdbc:mysql://localhost:3306/medicaldb","root","Ritika@1910");
            PreparedStatement pt = con.prepareStatement("insert into companytb values(?,?,?,?,?)");
            pt.setInt(1,Integer.valueOf(cid.getText()));
            pt.setString(2,cname.getText());
            pt.setString(3,cadd.getText());
            pt.setInt(4,Integer.valueOf(cexp.getText()));
            //pt.setDate(5,Mfd);
            //pt.setDate(6, Exp);
             pt.setInt(5,Integer.valueOf(cphone.getText()));
            int row = pt.executeUpdate();
            JOptionPane.showMessageDialog(this, "Medicine Successfully Added...");
            con.close();
            selectMod();

        }
        catch(SQLException e){

        }
    }//GEN-LAST:event_addMouseClicked

    private void deleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseClicked
        // TODO add your handling code here:
         if(cid.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Enter The Medicine To be Deleted.....");

        }
        else{
            try {
//                MDate = medmfd.getDate();
//                Mfd = new java.sql.Date(MDate.getTime());
//                EDate = medexp.getDate();
//                Exp = new java.sql.Date(EDate.getTime());
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/medicaldb","root","Ritika@1910");
                String id = cid.getText();
                String query = "Delete from companytb where comp_id="+id;
                st = con.createStatement();
                st.executeUpdate(query);
                selectMod();
                JOptionPane.showMessageDialog(this, "Medicine Deleted Successfully...");
            } catch (SQLException e) {
                // Logger.getLogger(Medcine.class.getName()).log(Level.SEVERE, null, ex);
                // e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Enter Id....");
            }

        }
    }//GEN-LAST:event_deleteMouseClicked

    private void updateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseClicked
        // TODO add your handling code here:
         if (cid.getText().isEmpty() || cname.getText().isEmpty() || cadd.getText().isEmpty() || cphone.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Missing Information...");
        } else {
            try {
//                 MDate = medmfd.getDate();
//        Mfd = new java.sql.Date(MDate.getTime());
//        EDate = medexp.getDate();
//        Exp = new java.sql.Date(EDate.getTime());
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/medicaldb", "root", "Ritika@1910");
                String updatequery = "update companytb set comp_name = '" + cname.getText() + "'" + ",comp_ad = " + cadd.getText() + "" + ",comp_exp = " + cexp.getText() + "" + ",comp_phone = " + cphone.getText() + "" + "where comp_id = " + cid.getText();
                st = con.createStatement();
                st.executeUpdate(updatequery);
                JOptionPane.showMessageDialog(this, "Company Updated Successfully...");
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_updateMouseClicked

    private void comptableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comptableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) comptable.getModel();
        int MyIndex = comptable.getSelectedRow();
        cid.setText(model.getValueAt(MyIndex, 0).toString());
        cname.setText(model.getValueAt(MyIndex, 1).toString());
        cadd.setText(model.getValueAt(MyIndex, 2).toString());
        cexp.setText(model.getValueAt(MyIndex, 3).toString());
        cphone.setText(model.getValueAt(MyIndex, 4).toString());
    }//GEN-LAST:event_comptableMouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
        new Welcome().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel11MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Company.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Company.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Company.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Company.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Company().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JTextField cadd;
    private javax.swing.JTextField cexp;
    private javax.swing.JTextField cid;
    private javax.swing.JTextField cname;
    private javax.swing.JTable comptable;
    private javax.swing.JTextField cphone;
    private javax.swing.JButton delete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
