/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package medicalportal;

import java.awt.print.PrinterException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Ritika Tiwari
 */
public class Selling extends javax.swing.JFrame {

    /**
     * Creates new form Selling
     */
    
    
    Connection con = null;
    Statement st = null;
    ResultSet rs = null;
    
    public Selling() {
        initComponents();
        showDate();
        selectMod();
    }
    
    
    public void showDate(){
        Date d = new Date();
        SimpleDateFormat s = new SimpleDateFormat("dd-MM-yyy");
        datelbl.setText(s.format(d));
    }

    
    
    
    
     private void selectMod(){
        
       try{
           con =DriverManager.getConnection("jdbc:mysql://localhost:3306/medicaldb","root","Ritika@1910");
           st = con.createStatement();
           rs = st.executeQuery("select * from medicinetb");
           medicinetable.setModel(DbUtils.resultSetToTableModel(rs));
       } 
       catch(SQLException e){
           JOptionPane.showMessageDialog(this, "Enter Details....");
           //e.printStackTrace();
       }
    }
     
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        add = new javax.swing.JButton();
        datelbl = new javax.swing.JLabel();
        billid = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        update = new javax.swing.JButton();
        qty = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        delete = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        med = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        billtxt = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        medicinetable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(null);

        add.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        add.setText("ADD TO BILL");
        add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addMouseClicked(evt);
            }
        });
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        jPanel1.add(add);
        add.setBounds(40, 270, 180, 34);

        datelbl.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        datelbl.setText("date");
        jPanel1.add(datelbl);
        datelbl.setBounds(780, 10, 109, 38);

        billid.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        billid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billidActionPerformed(evt);
            }
        });
        jPanel1.add(billid);
        billid.setBounds(120, 100, 173, 28);

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-logout-rounded-left-30.png"))); // NOI18N
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel11);
        jLabel11.setBounds(10, 0, 40, 40);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setText("COMPANIES LIST");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(520, 40, 206, 38);

        update.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        update.setText("PRINT");
        update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateMouseClicked(evt);
            }
        });
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        jPanel1.add(update);
        update.setBounds(390, 510, 120, 34);

        qty.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        qty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qtyActionPerformed(evt);
            }
        });
        jPanel1.add(qty);
        qty.setBounds(120, 220, 173, 28);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setText("BILL");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(460, 300, 40, 38);

        delete.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        delete.setText("DELETE");
        delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteMouseClicked(evt);
            }
        });
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        jPanel1.add(delete);
        delete.setBounds(570, 270, 120, 34);

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel9.setText("BILLING");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(380, 0, 120, 38);

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setText("BILL ID");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(10, 90, 109, 38);

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel8.setText("Seller");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(100, 30, 60, 38);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setText("MEDICINE");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 150, 109, 38);

        med.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jPanel1.add(med);
        med.setBounds(120, 160, 173, 28);

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setText("QTY");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 220, 109, 38);

        billtxt.setColumns(20);
        billtxt.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        billtxt.setRows(5);
        billtxt.setText("*******************************************MEDICAL CENTER************************************************");
        jScrollPane2.setViewportView(billtxt);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(170, 330, 670, 170);

        medicinetable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "MED_NAME", "MED_PRICE", "QUANTITY", "MFD_DATE", "EXP_DATE", "COMPANY"
            }
        ));
        medicinetable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                medicinetableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(medicinetable);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(300, 80, 670, 180);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/pinkblue1.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, -50, 990, 660);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 983, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setSize(new java.awt.Dimension(983, 561));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    int i = 0,price,medid,oldQty;
    private void addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseClicked
        // TODO add your handling code here:
        if(med.getText().isEmpty()||qty.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Missing Information");
        }
        i++;
       // update();
        if(i==1){
        billtxt.setText(billtxt.getText()+"\n"
                +"\t    ID            MEDICINE            QTY            PRICE            TOTAL      \n\t"
                + " "+i+"              "+med.getText()+"            "+qty.getText()+"                   "+price+"             "+Integer.valueOf(qty.getText())*price);
                i++;
        }else{
            billtxt.setText(billtxt.getText()+"\n\t"+i+"                "+med.getText()+"             "+qty.getText()+"            "+price+"                "+Integer.valueOf(qty.getText())*price);
        }
    }//GEN-LAST:event_addMouseClicked

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:a
    }//GEN-LAST:event_addActionPerformed

    private void billidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_billidActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateActionPerformed

    private void deleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseClicked
        // TODO add your handling code here:
   
    }//GEN-LAST:event_deleteMouseClicked

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteActionPerformed

    private void qtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qtyActionPerformed

    private void medicinetableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_medicinetableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) medicinetable.getModel();
        int MyIndex = medicinetable.getSelectedRow();
        med.setText(model.getValueAt(MyIndex, 1).toString());
        price = Integer.valueOf(model.getValueAt(MyIndex, 0).toString());
       

    }//GEN-LAST:event_medicinetableMouseClicked

    
    
    
    public void update(){
        int newQty;
        newQty = oldQty - Integer.valueOf(qty.getText());
        try{
        con = DriverManager.getConnection("jdbc:mysql://localhost:3306/medicaldb","root","Ritika@1910");
                String updatequery = "Update medicinetb set med_qty = "+newQty+""+" where med_id = "+med;
                st = con.createStatement();
                st.executeUpdate(updatequery);
                //JOptionPane.showMessageDialog(this, "Medicine Updated Successfully...");
                con.close();
            selectMod();
            }
            catch(SQLException e){
                e.printStackTrace();
            }
    }
    private void updateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseClicked
        try {
            // TODO add your handling code here:
            billtxt.print();
        } catch (PrinterException ex) {
            Logger.getLogger(Selling.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_updateMouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
        new Welcome().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel11MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Selling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Selling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Selling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Selling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Selling().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JTextField billid;
    private javax.swing.JTextArea billtxt;
    private javax.swing.JLabel datelbl;
    private javax.swing.JButton delete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField med;
    private javax.swing.JTable medicinetable;
    private javax.swing.JTextField qty;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
