/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package medicalportal;

/**
 *
 * @author Ritika Tiwari
 */
public class Welcome extends javax.swing.JFrame {

    /**
     * Creates new form Welcome
     */
    public Welcome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        sell = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        agents = new javax.swing.JButton();
        medi = new javax.swing.JButton();
        comp1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(null);

        sell.setBackground(new java.awt.Color(51, 255, 255));
        sell.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        sell.setForeground(new java.awt.Color(255, 255, 255));
        sell.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-money-bag-rupee-30 (2).png"))); // NOI18N
        sell.setText("SELLING");
        sell.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sellMouseClicked(evt);
            }
        });
        sell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sellActionPerformed(evt);
            }
        });
        jPanel1.add(sell);
        sell.setBounds(60, 270, 220, 50);

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-macos-close-30.png"))); // NOI18N
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel11);
        jLabel11.setBounds(660, 0, 30, 40);

        agents.setBackground(new java.awt.Color(51, 255, 255));
        agents.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        agents.setForeground(new java.awt.Color(255, 255, 255));
        agents.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-search-client-30.png"))); // NOI18N
        agents.setText("AGENTS");
        agents.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                agentsMouseClicked(evt);
            }
        });
        agents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agentsActionPerformed(evt);
            }
        });
        jPanel1.add(agents);
        agents.setBounds(60, 200, 220, 50);

        medi.setBackground(new java.awt.Color(51, 255, 255));
        medi.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        medi.setForeground(new java.awt.Color(255, 255, 255));
        medi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-medicine-24 (1).png"))); // NOI18N
        medi.setText("MEDICINE");
        medi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mediMouseClicked(evt);
            }
        });
        medi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mediActionPerformed(evt);
            }
        });
        jPanel1.add(medi);
        medi.setBounds(60, 60, 220, 50);

        comp1.setBackground(new java.awt.Color(51, 255, 255));
        comp1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        comp1.setForeground(new java.awt.Color(255, 255, 255));
        comp1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-mastercard-credit-card-30.png"))); // NOI18N
        comp1.setText("COMPANY");
        comp1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comp1MouseClicked(evt);
            }
        });
        comp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comp1ActionPerformed(evt);
            }
        });
        jPanel1.add(comp1);
        comp1.setBounds(60, 130, 220, 50);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bg.png"))); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(0, 0, 700, 386);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 698, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(698, 382));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void sellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sellActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sellActionPerformed

    private void mediActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mediActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mediActionPerformed

    private void agentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agentsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agentsActionPerformed

    private void comp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comp1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comp1ActionPerformed

    private void mediMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mediMouseClicked
        // TODO add your handling code here:
         java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Medicine().setVisible(true);
            }
        });
    }//GEN-LAST:event_mediMouseClicked

    private void sellMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sellMouseClicked
        // TODO add your handling code here:
         java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Selling().setVisible(true);
            }
        });
    }//GEN-LAST:event_sellMouseClicked

    private void comp1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comp1MouseClicked
        // TODO add your handling code here:
         java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Company().setVisible(true);
            }
        });
    }//GEN-LAST:event_comp1MouseClicked

    private void agentsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agentsMouseClicked
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Agents().setVisible(true);
            }
        });
    }//GEN-LAST:event_agentsMouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
        System.exit(0);

    }//GEN-LAST:event_jLabel11MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Welcome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agents;
    private javax.swing.JButton comp1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton medi;
    private javax.swing.JButton sell;
    // End of variables declaration//GEN-END:variables
}
